### ISSUE TITLE
xmldom version not available

### ISSUE THREAD

**Issue by coolbox** [mapbox/tcx#1]
I'm trying to `npm install` the package but i keep getting the following error:

```
No compatible version found: xmldom@'>=3.4.0-0 <3.5.0-0'
```

Looking at the xmldom package page (https://www.npmjs.org/package/xmldom), it looks like the most recent version is: 0.1.19.

Am i missing something, or doing something wrong?

**Comment by arsgeografica** [comment]
For the added convenience, could you update the dist tarball at npmjs.org?

**Comment by tmcw** [comment]
Just released 0.0.1 with this fix.
